server.port=8080

# WebSocket
websocket.allowed-origins=http://localhost:4200

# Logging
logging.level.com.yourcaryourway=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
